config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get '/users/', to: 'users#list'
  get '/users/:id', to: 'users#profile'

  resources :posts do
    resources :comments
  end
  root 'posts#index'
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post
  validates :name, presence: true
  validates :content, presence: true, length: {maximum: 140}
end

app/models/post.rb
class Post < ActiveRecord::Base
  # associations
   has_many :comments, dependent: :destroy
   belongs_to :user


  # validations
   validates :title,   presence: true, length: { in: 2..25 }
   validates :content, presence: true, length: { in: 3..140 }

  # FriendlyId
   extend FriendlyId
   friendly_id :title, use: :slugged

  # paperclip
    has_attached_file :image, styles: { post: "700x400>",
    thumb: "100x100>" }, default_url: "/images/:style/missing.png"
    #validates_attachment_content_type :article, content_type: /\Aimage\/.*\Z/
    validates_attachment :image, content_type: { content_type: ["image/jpg",
                                      "image/jpeg", "image/png", "image/gif"] }
  end

app/models/user.rb
class User < ActiveRecord::Base

  # associations
   has_many :posts, dependent: :destroy

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # paperclip profile image
  has_attached_file :avatar, styles: { thumb: "100x100>", tiny: "50x50" },
                                      default_url: "/images/:style/missing.png"
  validates_attachment :avatar, content_type: { content_type: ["image/jpg","image/jpeg",
                                                              "image/png", "image/gif"] }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_filter :configure_permitted_parameters, if: :devise_controller?

  protect_from_forgery with: :exception

  protected
    def configure_permitted_parameters
     devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:username, :email,
                    :password, :avatar, :password_confirmation, :remember_me) }
     devise_parameter_sanitizer.for(:sign_in) { |u| u.permit(:login, :username,
                                              :email, :password, :remember_me) }
     devise_parameter_sanitizer.for(:account_update) { |u| u.permit(:username,
        :email, :password, :avatar, :password_confirmation, :current_password) }
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def create
    @post = Post.friendly.find(params[:post_id])
    @comments = @post.comments.create(params[:comment].permit(:name, :content))

    redirect_to post_path(@post)
  end

  def destroy
    @post = Post.friendly.find(params[:post_id])
    @comments = @post.comments.find(params[:id])
    @comments.destroy
    flash[:notice] = "The comment has been deleted."

    redirect_to post_path(@post)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!

  def index
    @posts = Post.all.order('created_at DESC')
  end

  def view
  end

  def new
    @post = current_user.posts.new
  end

  def create
    @post = current_user.posts.new(post_params)
    
    if @post.save
      redirect_to @post
      flash[:notice] = "The post has been created."
    else
      render 'new'
      flash[:alert] = "Error has occurred. Please make sure that your post
                                                    is valid and try again."
    end
  end

  def show
    find_post
  end

  def edit
    find_post
  end

  def update
    find_post
    if @post.update(params[:post].permit(:title, :content))
      redirect_to @post
      flash[:notice] = "The post has been updated."
    else
      render 'edit'
      show_post_error
    end
  end

  def destroy
    find_post
    @post.destroy
    redirect_to root_path
    flash[:notice] = "The post has been deleted."
  end

  private

  def show_post_error
    flash[:alert] = "Error has occurred. Please validate the data you submitting
                                                                  and try again."
  end

  def find_post
    @post = Post.friendly.find(params[:id])
  end

  def post_params
    params.require(:post).permit(:title, :content, :image, :userid)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def list
    @users = User.all
  end

  def profile
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/_comment.html.erb
<p><%= comment.name %></p><br>
<p><%= comment.content %></p>
<p><%= time_ago_in_words(comment.created_at) %> Ago</p>

<p> <%= link_to 'Delete Note', [comment.post, comment], method: :delete,
    data: {confirm: 'Are you sure?'} %>
</p>

app/views/comments/_form.html.erb
<%= bootstrap_form_for([@post, @post.comments.build]) do |f| %>
  <%= f.text_field :name, label: "User name" %>
  <%= f.text_area :content, label: "Notes" %>
  <%= f.submit %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Tumblr</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <% if notice %>
    <p class="alert alert-success"><%= notice %></p>
  <% elsif alert %>
    <p class="alert alert-danger"><%= alert %></p>
  <% end %>


<%= render 'shared/nav_bar.html.erb' %>


<div class="wrapper">
  <div class="container">
    <%= yield %>
  </div>
</div>

</body>
</html>

app/views/posts/_form.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    <h3 class="panel-title">
      Posting us: <%= current_user.username %>, Not you? <%= link_to("Sign out", destroy_user_session_path, :method => :delete) %>
    </h3>
  </div>
  <div class="panel-body">
    <%= bootstrap_form_for @post, url: post_path(@post) do |f| %>
      <%= f.file_field :image, as: :file %>
      <%= f.text_field :title %>
      <%= f.text_area :content %>
      <%= f.submit %>
    <% end %>
    <br>
  </div>
</div>

app/views/posts/edit.html.erb
<div class="col-md-12 col-ms-12">
  <h3>Edit post</h3>
  <br>
  <%= render 'form' %>
</div>

app/views/posts/index.html.erb
<div class="col-md-12 col-ms-12">
  <% @posts.each do |post| %>
    <div class="panel panel-default">
      <div class="panel-heading">
        <h6 class="panel-title">
          <div class="raw">
            <div class="col-md-offset-1">
              <%= link_to (image_tag User.find(post.user_id).avatar.url(:tiny)),
              "#{"users/#{post.user_id}"}" %>
              <%= link_to "#{User.find(post.user_id).username}",
              "users/#{post.user_id}" %>
              <br>
            </div>
          </div>
        </h6>
        </div>
        <div class="raw">
          <div class="col-md-offset-1">
            <div class="panel-body">
              <% if post.image? %>
                <%= link_to (image_tag post.image.url(:thumb)), post %>
              <% end %>
              <br>
              <br>
              <p><small><%= truncate(post.content, length:65) %></small></p>
                <% if user_signed_in? %>
                  <%= link_to '<i class="glyphicon glyphicon-edit"></i>'.html_safe,
                   edit_post_path(post), class: 'btn btn-default' %>
                  <%= link_to '<i class="glyphicon glyphicon-trash"></i>'.html_safe,
                   post_path(post), method: :delete,
                    data: { confirm: "The post will be deleted. Click ok to continue." },
                     class: 'btn btn-default' %>
                <% end %>
                </p>
          </div>
          </div>
        </div>
    </div>
  <% end %>
</div>

app/views/posts/new.html.erb
<div class="col-md-12 col-ms-12">
  <h3>New Post</h3>
  <br>
  <%= render 'form' %>
</div>

app/views/posts/show.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    <h3 class "panel-title">
      <%= link_to (image_tag User.find(@post.user_id).avatar.url(:tiny)),"#{"users/#{@post.user_id}"}" %>
      <%= link_to "#{User.find(@post.user_id).username}","users/#{@post.user_id}" %>
      <%= @post.title %>
      <p><small><%= time_ago_in_words(@post.created_at) %> ago.<small></p>
    </div>
    <div class="raw">
      <div class="container">
        <div class="cal-md-2">
            <% if @post.image? %>
              <%= image_tag @post.image.url(:post), class: "img-responsive img-rounded center-block" %>
            <% end %>
          <br>
          <br>
          <p><%= @post.content %></p>
          <br>
          <br>
          <% if user_signed_in? %>
            <%= link_to 'Edit', edit_post_path(@post) %>
            <%= link_to "Delete", post_path(@post), method: :delete, data: { confirm: "Are you sure?" } %>
          <% end %>
          <br>
          <hr>
          <p><%= @post.comments.count %> comments</p>
          <br>
          <p><small><%= render @post.comments %></small></p>
          <%= render "comments/form" %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/shared/_nav_bar.html.erb
<nav class="navbar navbar-default transparent">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Tumblr", root_path, class: 'navbar-brand' %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <% if current_user %>
          <li><%= link_to '<i class="glyphicon glyphicon-home"></i>'.html_safe, "/users/#{current_user.id}", class: 'btn btn-default' %></li>
        <% end %>
        <li><%= link_to '<i class="glyphicon glyphicon glyphicon-globe"></i>'.html_safe, users_path, class: 'btn btn-default' %></li>
        <li><%= link_to '<i class="glyphicon glyphicon-comment"></i>'.html_safe, root_path, class: 'btn btn-default' %></li>
        <li><%= link_to '<i class="glyphicon glyphicon-flash"></i>'.html_safe, root_path, class: 'btn btn-default' %></li>
        <li><%= link_to '<i class="glyphicon glyphicon-user"></i>'.html_safe, root_path, class: 'btn btn-default' %></li>
        <li><%= link_to '<i class="glyphicon glyphicon-pencil"></i>'.html_safe, new_post_path(@post), class: 'btn btn-default' %></li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/users/list.html.erb
<h3>Trending blogs</h3>

<% @users.each do |user| %>
  <div class="panel panel-default">
    <div class="panel-heading">
      <h3 class="panel-title"><%=link_to user.username, "/users/#{user.id}" %></div>
        <div class="raw">
          <div class="container">
            <div class="cal-md-2">
              <%= link_to (image_tag user.avatar.url(:thumb)), "/users/#{user.id}" %><hr>
              <%= link_to "Follow", "#", class: "btn btn-default" %><br><br>
              <% end %>
            </div>
          </div>
        </div>
    </div>
  </div>

app/views/users/profile.html.erb
<p><%= @user.username %><br></p>
   <%= image_tag @user.avatar.url(:thumb) %><br>
<p><%= @user.created_at %></p><br>